export const SET_BUDGET_SUM = 'SET_BUDGET_SUM';
export const SET_MON_COST_VALUE = 'SET_MON_COST_VALUE';
export const SET_CURRENT_SCHEME_ID = 'SET_CURRENT_SCHEME_ID';
export const SET_CURRENT_SCHEME_NAME = 'SET_CURRENT_SCHEME_NAME';

export const SET_SCHEME_LIST = 'SET_SCHEME_LIST';
export const SET_COLLECTION_LIST = 'SET_COLLECTION_LIST';

export const SET_TARGET_SCHEME = 'SET_TARGET_SCHEME';
export const SET_TARGET_COLLECTION = 'SET_TARGET_COLLECTION';